/**
 * ChunkContentService — what's actually in each map chunk.
 *
 * Lazy-loads public/chunk-content.json (generated by
 * scripts/sync-chunk-content.mjs from the One Chunk Man Chunk Picker's data
 * export — credit: source-chunk/chunk-picker-v2) and answers two questions:
 *   - contentFor(cx, cy): what's in this one chunk?
 *   - aggregate(chunks):  what does this whole group of chunks offer?
 *
 * The JSON uses canonical OSRS region ids (regionId = cx * 256 + cy), which is
 * exactly our map's chunk coordinate space (see utils/mapCoords.ts).
 * Fail-safe: if the fetch fails the map simply shows no content panel.
 */

export interface ChunkMonster { name: string; count: number; slayer: number | null }
export interface ChunkContent {
  name?: string;
  monsters: ChunkMonster[];
  npcs: string[];
  objects: [string, number][];
  shops: string[];
  /** quest name → 'first' (starts here) | 'step' (a step happens here) */
  quests: Record<string, 'first' | 'step'>;
  /** diary area → task refs (e.g. "EA5, MD6") */
  diaries: Record<string, string>;
  /** clue tier → step count */
  clues: Record<string, number>;
  /** ground item spawns */
  spawns: string[];
}

/** Compact on-disk shape (see sync-chunk-content.mjs). */
interface RawEntry {
  n?: string;
  m?: [string, number, number?][];
  p?: string[];
  o?: [string, number][];
  s?: string[];
  q?: Record<string, 'first' | 'step'>;
  d?: Record<string, string>;
  c?: Record<string, number>;
  i?: string[];
}
/** A Slayer master's assignable monster: gating + assignment weight. */
export interface SlayerAssignment {
  weight: number;
  /** Combat level needed before the master will assign it. */
  combat?: number;
  /** Slayer level needed to damage/be assigned it. */
  slayer?: number;
  /** Unlock requirements (e.g. "Priest in Peril Complete the quest"). */
  req?: string[];
}
export type SlayerMasters = Record<string, Record<string, SlayerAssignment>>;

/** A travel/agility shortcut surfaced from the picker's challenge tables. */
export interface Shortcut {
  name: string;
  skill: string;
  level: number;
  /** Interactable object names — used to locate the shortcut's chunk(s). */
  objects: string[];
  chunks: string[];
}

/** Undirected chunk transport graph: region id → linked region ids. */
export type ConnectGraph = Record<string, string[]>;

/** A map marker (star / impling / crop circle / crime / clue step). */
export interface OverlayPoint {
  /** World coordinates (for precise placement). */
  x: number;
  y: number;
  /** The chunk this point falls in. */
  cx: number;
  cy: number;
  /** Clue tier (Hard/Elite/…), clue points only. */
  t?: string;
  /** Clue hint text, clue points only. */
  h?: string;
}
export type Overlays = Record<string, OverlayPoint[]>;

/** Per-skill yields: skill → method/node name → [item, rate] pairs. */
export type SkillItems = Record<string, Record<string, [string, string][]>>;

/**
 * Access/use requirements, keyed *per chunk* so a generic entity (a "Man", a
 * "Banker") only carries the requirement in the chunk it applies to:
 *   category → entity name → { chunkId | "*" (Items, global): requirement strings }
 */
export type TaskUnlockCategory = 'Items' | 'Monsters' | 'NPCs' | 'Objects' | 'Shops' | 'Spawns';
export type TaskUnlocks = Partial<Record<TaskUnlockCategory, Record<string, Record<string, string[]>>>>;
/** Our entity kinds → the taskUnlocks category they map to. */
const TASK_CATEGORY: Record<EntityKind, TaskUnlockCategory> = {
  monster: 'Monsters', npc: 'NPCs', object: 'Objects', shop: 'Shops', spawn: 'Spawns', quest: 'Items',
};

interface RawDoc {
  version: number;
  source: string;
  sourceMeta?: {
    repository: string;
    commit: string;
    blobSha: string;
    rawSha256: string;
    policyVersion: number;
  };
  chunks: Record<string, RawEntry>;
  connect?: ConnectGraph;
  slayerMasters?: SlayerMasters;
  shortcuts?: Shortcut[];
  shopItems?: Record<string, string[]>;
  /** Monster name → the item names it drops. */
  drops?: Record<string, string[]>;
  /** Map marker overlays, keyed by category. */
  overlays?: Overlays;
  /** Per-skill gathering/processing yields. */
  skillItems?: SkillItems;
  /** Access/use requirements per entity (quests, slayer tasks, guild access). */
  taskUnlocks?: TaskUnlocks;
  /** Per-chunk ENTRY requirements: chunkId → quest(s) needed to enter at all. */
  questSections?: Record<string, string[]>;
  /** Chunk ids that contain a bank. */
  banks?: string[];
  /** Faceted categories (food/boost/boss/…) → the chunk ids that contain them. */
  tags?: Record<string, string[]>;
}

const decode = (e: RawEntry): ChunkContent => ({
  name: e.n,
  monsters: (e.m ?? []).map(([name, count, slayer]) => ({ name, count, slayer: slayer ?? null })),
  npcs: e.p ?? [],
  objects: e.o ?? [],
  shops: e.s ?? [],
  quests: e.q ?? {},
  diaries: e.d ?? {},
  clues: e.c ?? {},
  spawns: e.i ?? [],
});

/** Merge many chunks' content into one region-level summary. Pure — tested. */
export function aggregateContent(entries: ChunkContent[]): ChunkContent {
  const monsters = new Map<string, ChunkMonster>();
  const npcs = new Set<string>();
  const objects = new Map<string, number>();
  const shops = new Set<string>();
  const quests: Record<string, 'first' | 'step'> = {};
  const diaries: Record<string, string> = {};
  const clues: Record<string, number> = {};
  const spawns = new Set<string>();

  for (const e of entries) {
    for (const m of e.monsters) {
      const cur = monsters.get(m.name);
      if (cur) {
        cur.count += m.count;
        if (m.slayer != null) cur.slayer = cur.slayer == null ? m.slayer : Math.min(cur.slayer, m.slayer);
      } else {
        monsters.set(m.name, { ...m });
      }
    }
    for (const n of e.npcs) npcs.add(n);
    for (const [name, count] of e.objects) objects.set(name, (objects.get(name) ?? 0) + count);
    for (const s of e.shops) shops.add(s);
    for (const [q, kind] of Object.entries(e.quests)) {
      if (kind === 'first' || !(q in quests)) quests[q] = kind;
    }
    for (const [area, refs] of Object.entries(e.diaries)) {
      diaries[area] = area in diaries ? `${diaries[area]}, ${refs}` : refs;
    }
    for (const [tier, n] of Object.entries(e.clues)) clues[tier] = (clues[tier] ?? 0) + n;
    for (const s of e.spawns) spawns.add(s);
  }

  return {
    monsters: [...monsters.values()].sort((a, b) => b.count - a.count),
    npcs: [...npcs].sort(),
    objects: [...objects.entries()].sort((a, b) => b[1] - a[1]),
    shops: [...shops].sort(),
    quests,
    diaries,
    clues,
    spawns: [...spawns].sort(),
  };
}

export type EntityKind = 'monster' | 'object' | 'npc' | 'spawn' | 'shop' | 'quest';

export interface EntityLocation {
  cx: number;
  cy: number;
  count?: number;
  /** Quest entries only: does the quest start here or just have a step? */
  role?: 'first' | 'step';
}

export interface EntityHit {
  name: string;
  kind: EntityKind;
  locations: EntityLocation[];
}

// Bump when public/chunk-content.json changes so the fetch URL changes and
// browsers don't serve a stale cached copy (the filename itself never changes).
const DATA_REV = 10;

class ChunkContentService {
  private doc: RawDoc | null = null;
  private promise: Promise<boolean> | null = null;
  private index: Map<string, EntityHit> | null = null;
  error: string | null = null;

  get ready() { return this.doc != null; }

  sourceMetadata(): RawDoc['sourceMeta'] | null {
    return this.doc?.sourceMeta ?? null;
  }

  /** Idempotent lazy init; resolves false (and sets .error) on failure. */
  init(): Promise<boolean> {
    if (this.doc) return Promise.resolve(true);
    if (!this.promise) {
      const base = (import.meta as any).env?.BASE_URL ?? '/';
      this.promise = fetch(`${base}chunk-content.json?v=${DATA_REV}`)
        .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
        .then((doc: RawDoc) => { this.doc = doc; return true; })
        .catch((err: Error) => {
          this.error = err.message;
          this.promise = null; // allow retry
          return false;
        });
    }
    return this.promise;
  }

  allChunkCoords(): { cx: number; cy: number }[] {
    return Object.keys(this.doc?.chunks ?? {})
      .map((id) => {
        const value = Number(id);
        return { cx: Math.floor(value / 256), cy: value % 256 };
      })
      .sort((left, right) => left.cx - right.cx || left.cy - right.cy);
  }

  contentFor(cx: number, cy: number): ChunkContent | null {
    const e = this.doc?.chunks[String(cx * 256 + cy)];
    return e ? decode(e) : null;
  }

  /** Region-level aggregate over a chunk list (missing chunks are skipped). */
  aggregate(chunks: { cx: number; cy: number }[]): ChunkContent {
    const entries: ChunkContent[] = [];
    for (const { cx, cy } of chunks) {
      const c = this.contentFor(cx, cy);
      if (c) entries.push(c);
    }
    return aggregateContent(entries);
  }

  // ── Entity → locations index ────────────────────────────────────────────
  // "Where can I find a Yew tree / Chaos Druid / Cook's Assistant?" — built
  // once, lazily, from the loaded dataset. ~3k entities; fine in memory.

  private buildIndex(): Map<string, EntityHit> {
    const index = new Map<string, EntityHit>();
    const add = (kind: EntityKind, name: string, loc: EntityLocation) => {
      const k = `${kind}|${name.toLowerCase()}`;
      const hit = index.get(k);
      if (hit) hit.locations.push(loc);
      else index.set(k, { name, kind, locations: [loc] });
    };
    for (const [id, e] of Object.entries(this.doc?.chunks ?? {})) {
      const cx = Math.floor(+id / 256), cy = +id % 256;
      for (const [name, count] of (e.m ?? [])) add('monster', name, { cx, cy, count });
      for (const [name, count] of (e.o ?? [])) add('object', name, { cx, cy, count });
      for (const name of (e.p ?? [])) add('npc', name, { cx, cy });
      for (const name of (e.i ?? [])) add('spawn', name, { cx, cy });
      for (const name of (e.s ?? [])) add('shop', name, { cx, cy });
      for (const [name, role] of Object.entries(e.q ?? {})) add('quest', name, { cx, cy, role });
    }
    return index;
  }

  private getIndex(): Map<string, EntityHit> | null {
    if (!this.doc) return null;
    if (!this.index) this.index = this.buildIndex();
    return this.index;
  }

  /** Exact (case-insensitive) lookup, first matching kind wins. */
  entityLocations(name: string, kinds: EntityKind[] = ['monster', 'object', 'npc', 'spawn', 'shop', 'quest']): EntityHit | null {
    const index = this.getIndex();
    if (!index) return null;
    const lower = name.toLowerCase();
    for (const kind of kinds) {
      const hit = index.get(`${kind}|${lower}`);
      if (hit) return hit;
    }
    return null;
  }

  /** Every indexed entity of one kind (e.g. all shops in Gielinor). */
  entitiesOfKind(kind: EntityKind): EntityHit[] {
    const index = this.getIndex();
    if (!index) return [];
    const out: EntityHit[] = [];
    for (const hit of index.values()) if (hit.kind === kind) out.push(hit);
    return out;
  }

  /** The undirected chunk transport graph (boats/teleports/stairs/shortcuts). */
  connectGraph(): ConnectGraph { return this.doc?.connect ?? {}; }

  /** Slayer master → assignable monster tables. */
  slayerMasters(): SlayerMasters { return this.doc?.slayerMasters ?? {}; }

  /** Travel/agility shortcuts with level + the object that triggers them. */
  shortcuts(): Shortcut[] { return this.doc?.shortcuts ?? []; }

  /** Map marker overlays (stars, implings, crop circles, crime, clues). */
  overlays(): Overlays { return this.doc?.overlays ?? {}; }

  /** Overlay category names that actually have points. */
  overlayCategories(): string[] { return Object.keys(this.doc?.overlays ?? {}); }

  /** Per-skill gathering/processing yields. */
  skillItems(): SkillItems { return this.doc?.skillItems ?? {}; }

  // Access/use requirements (quests / slayer tasks / guild access), built lazily
  // into a case-insensitive lookup keyed by "category|name" → { chunkId: reqs }.
  private taskIdx: Map<string, Record<string, string[]>> | null = null;
  private getTaskIdx(): Map<string, Record<string, string[]>> | null {
    if (!this.doc) return null;
    if (!this.taskIdx) {
      const idx = new Map<string, Record<string, string[]>>();
      for (const [cat, entries] of Object.entries(this.doc.taskUnlocks ?? {})) {
        for (const [name, byChunk] of Object.entries(entries)) idx.set(`${cat}|${name.toLowerCase()}`, byChunk);
      }
      this.taskIdx = idx;
    }
    return this.taskIdx;
  }

  /**
   * Access/use requirements for a named entity *in a specific chunk* — e.g.
   * "Access the fishing guild", "Dragon Slayer I". Keyed per chunk so a generic
   * entity only reports the requirement where it actually applies. Returns []
   * when there's no requirement for this entity in this chunk.
   */
  taskRequirements(name: string, kind: EntityKind, cx: number, cy: number): string[] {
    const byChunk = this.getTaskIdx()?.get(`${TASK_CATEGORY[kind]}|${name.toLowerCase()}`);
    return byChunk?.[String(cx * 256 + cy)] ?? [];
  }

  /** Global wield/use requirement for an item (location-less). */
  itemRequirements(name: string): string[] {
    return this.getTaskIdx()?.get(`Items|${name.toLowerCase()}`)?.['*'] ?? [];
  }

  // Item → the chunks it can be obtained in (shops selling it + monsters
  // dropping it), built lazily by inverting shopItems / drops and resolving each
  // host's locations through the entity index.
  private itemSrcIdx: Map<string, EntityLocation[]> | null = null;
  private buildItemSrcIdx(): Map<string, EntityLocation[]> {
    const idx = new Map<string, EntityLocation[]>();
    const addSources = (items: string[], host: string, kind: EntityKind) => {
      const hit = this.entityLocations(host, [kind]);
      if (!hit) return;
      for (const item of items) {
        const k = item.toLowerCase();
        const arr = idx.get(k);
        if (arr) arr.push(...hit.locations);
        else idx.set(k, [...hit.locations]);
      }
    };
    for (const [shop, items] of Object.entries(this.doc?.shopItems ?? {})) addSources(items, shop, 'shop');
    for (const [mon, items] of Object.entries(this.doc?.drops ?? {})) addSources(items, mon, 'monster');
    return idx;
  }

  /** Chunks where an item can be obtained (shops + drops). Empty when unknown. */
  itemSourceChunks(itemName: string): EntityLocation[] {
    if (!this.doc) return [];
    if (!this.itemSrcIdx) this.itemSrcIdx = this.buildItemSrcIdx();
    return this.itemSrcIdx.get(itemName.toLowerCase()) ?? [];
  }

  /**
   * Slayer task → the chunks its monster appears in, for the RuneLite plugin's
   * locked-slayer warning. Keyed by a normalised task name (lowercased, trailing
   * 's' dropped) so the plugin can match the assignment chat. Built from the FULL
   * (uncapped) monster index, so coverage is complete — unlike the slim
   * chunkContentLite "mon" list which caps at a few per chunk.
   */
  slayerReachIndex(): Record<string, { cx: number; cy: number }[]> {
    if (!this.doc) return {};
    const norm = (s: string) => {
      const t = s.toLowerCase().trim();
      return t.endsWith('s') ? t.slice(0, -1) : t;
    };
    // normalised monster name → its chunks (full, uncapped)
    const monIdx = new Map<string, { cx: number; cy: number }[]>();
    for (const hit of this.entitiesOfKind('monster')) {
      monIdx.set(norm(hit.name), hit.locations.map((l) => ({ cx: l.cx, cy: l.cy })));
    }
    // every assignable task name across all masters
    const cats = new Set<string>();
    for (const tasks of Object.values(this.slayerMasters())) {
      for (const t of Object.keys(tasks)) cats.add(t);
    }
    const out: Record<string, { cx: number; cy: number }[]> = {};
    for (const cat of cats) {
      const k = norm(cat);
      let chunks = monIdx.get(k);
      if (!chunks) {
        // fall back to fuzzy containment (e.g. "fever spider" task vs "Fever spider")
        const acc: { cx: number; cy: number }[] = [];
        for (const [mn, ch] of monIdx) if (mn === k || mn.includes(k) || k.includes(mn)) acc.push(...ch);
        chunks = acc;
      }
      if (chunks.length) {
        const seen = new Set<string>();
        out[k] = chunks.filter((c) => { const id = `${c.cx},${c.cy}`; if (seen.has(id)) return false; seen.add(id); return true; });
      }
    }
    return out;
  }

  /** Per-chunk entry requirements: chunkId → quest(s) needed to enter. */
  questSections(): Record<string, string[]> { return this.doc?.questSections ?? {}; }

  /** Quest(s) you must have to enter this chunk at all ([] when ungated). */
  chunkEntryRequirements(cx: number, cy: number): string[] {
    return this.doc?.questSections?.[String(cx * 256 + cy)] ?? [];
  }

  // ── Banks + faceted categories ────────────────────────────────────────────
  private bankSet: Set<string> | null = null;
  private getBankSet(): Set<string> {
    if (!this.bankSet) this.bankSet = new Set(this.doc?.banks ?? []);
    return this.bankSet;
  }
  /** Does this chunk contain a bank? */
  hasBank(cx: number, cy: number): boolean { return this.getBankSet().has(String(cx * 256 + cy)); }

  /** Available faceted categories ("bank" is synthesised from the bank set). */
  tagList(): string[] {
    const tags = Object.keys(this.doc?.tags ?? {});
    return (this.doc?.banks?.length ? ['bank', ...tags] : tags);
  }

  /** Chunks (cx,cy) that contain a given category — "bank", "boss", "food", … */
  tagChunks(tag: string): { cx: number; cy: number }[] {
    const ids = tag === 'bank' ? (this.doc?.banks ?? []) : (this.doc?.tags?.[tag] ?? []);
    return ids.map(id => { const n = +id; return { cx: Math.floor(n / 256), cy: n % 256 }; });
  }

  /** The yield methods for one skill (e.g. Mining → {"Gem rocks": [...], …}). */
  skillYields(skill: string): Record<string, [string, string][]> {
    const all = this.doc?.skillItems ?? {};
    return all[skill] ?? all[Object.keys(all).find(k => k.toLowerCase() === skill.toLowerCase()) ?? ''] ?? {};
  }

  // Item → monsters that drop it, built lazily by inverting the drops table.
  private itemIdx: Map<string, { name: string; monsters: string[] }> | null = null;
  private getItemIdx(): Map<string, { name: string; monsters: string[] }> | null {
    if (!this.doc) return null;
    if (!this.itemIdx) {
      const idx = new Map<string, { name: string; monsters: string[] }>();
      for (const [monster, items] of Object.entries(this.doc.drops ?? {})) {
        for (const item of items) {
          const key = item.toLowerCase();
          let e = idx.get(key);
          if (!e) { e = { name: item, monsters: [] }; idx.set(key, e); }
          e.monsters.push(monster);
        }
      }
      this.itemIdx = idx;
    }
    return this.itemIdx;
  }

  /** Monsters that drop a given item (case-insensitive exact name). */
  itemSources(itemName: string): string[] {
    return this.getItemIdx()?.get(itemName.toLowerCase())?.monsters ?? [];
  }

  /** Ranked item-name search across every drop table — for "where do I get X". */
  searchItems(query: string, limit = 6): { name: string; sources: number }[] {
    const idx = this.getItemIdx();
    const q = query.trim().toLowerCase();
    if (!idx || q.length < 2) return [];
    const scored: { name: string; sources: number; score: number }[] = [];
    for (const e of idx.values()) {
      const n = e.name.toLowerCase();
      let score = 0;
      if (n === q) score = 3; else if (n.startsWith(q)) score = 2; else if (n.includes(q)) score = 1;
      if (score) scored.push({ name: e.name, sources: e.monsters.length, score });
    }
    return scored
      .sort((a, b) => b.score - a.score || b.sources - a.sources || a.name.localeCompare(b.name))
      .slice(0, limit)
      .map(({ name, sources }) => ({ name, sources }));
  }

  /** What a named shop sells (case-insensitive, tolerant of a trailing dot). */
  shopStock(name: string): string[] {
    const items = this.doc?.shopItems;
    if (!items) return [];
    const key = name.replace(/\.$/, '');
    return items[key] ?? items[key.toLowerCase()] ??
      Object.entries(items).find(([k]) => k.toLowerCase() === key.toLowerCase())?.[1] ?? [];
  }

  /** Ranked substring search across every entity in Gielinor. */
  searchEntities(query: string, limit = 8): EntityHit[] {
    const index = this.getIndex();
    const q = query.trim().toLowerCase();
    if (!index || q.length < 2) return [];
    const scored: { hit: EntityHit; score: number }[] = [];
    for (const hit of index.values()) {
      const n = hit.name.toLowerCase();
      let score = 0;
      if (n === q) score = 3;
      else if (n.startsWith(q)) score = 2;
      else if (n.includes(q)) score = 1;
      if (score) scored.push({ hit, score });
    }
    return scored
      .sort((a, b) => b.score - a.score || b.hit.locations.length - a.hit.locations.length || a.hit.name.localeCompare(b.hit.name))
      .slice(0, limit)
      .map(s => s.hit);
  }
}

export const chunkContentService = new ChunkContentService();
