/**
 * ChunkContentService — what's actually in each map chunk.
 *
 * Lazy-loads public/chunk-content.json (generated by
 * scripts/sync-chunk-content.mjs from the One Chunk Man Chunk Picker's data
 * export — credit: source-chunk/chunk-picker-v2) and answers two questions:
 *   - contentFor(cx, cy): what's in this one chunk?
 *   - aggregate(chunks):  what does this whole group of chunks offer?
 *
 * The JSON uses canonical OSRS region ids (regionId = cx * 256 + cy), which is
 * exactly our map's chunk coordinate space (see utils/mapCoords.ts).
 * Fail-safe: if the fetch fails the map simply shows no content panel.
 */

export interface ChunkMonster { name: string; count: number; slayer: number | null }
export interface ChunkContent {
  name?: string;
  monsters: ChunkMonster[];
  npcs: string[];
  objects: [string, number][];
  shops: string[];
  /** quest name → 'first' (starts here) | 'step' (a step happens here) */
  quests: Record<string, 'first' | 'step'>;
  /** diary area → task refs (e.g. "EA5, MD6") */
  diaries: Record<string, string>;
  /** clue tier → step count */
  clues: Record<string, number>;
  /** ground item spawns */
  spawns: string[];
}

/** Compact on-disk shape (see sync-chunk-content.mjs). */
interface RawEntry {
  n?: string;
  m?: [string, number, number?][];
  p?: string[];
  o?: [string, number][];
  s?: string[];
  q?: Record<string, 'first' | 'step'>;
  d?: Record<string, string>;
  c?: Record<string, number>;
  i?: string[];
}
interface RawDoc { version: number; source: string; chunks: Record<string, RawEntry> }

const decode = (e: RawEntry): ChunkContent => ({
  name: e.n,
  monsters: (e.m ?? []).map(([name, count, slayer]) => ({ name, count, slayer: slayer ?? null })),
  npcs: e.p ?? [],
  objects: e.o ?? [],
  shops: e.s ?? [],
  quests: e.q ?? {},
  diaries: e.d ?? {},
  clues: e.c ?? {},
  spawns: e.i ?? [],
});

/** Merge many chunks' content into one region-level summary. Pure — tested. */
export function aggregateContent(entries: ChunkContent[]): ChunkContent {
  const monsters = new Map<string, ChunkMonster>();
  const npcs = new Set<string>();
  const objects = new Map<string, number>();
  const shops = new Set<string>();
  const quests: Record<string, 'first' | 'step'> = {};
  const diaries: Record<string, string> = {};
  const clues: Record<string, number> = {};
  const spawns = new Set<string>();

  for (const e of entries) {
    for (const m of e.monsters) {
      const cur = monsters.get(m.name);
      if (cur) {
        cur.count += m.count;
        if (m.slayer != null) cur.slayer = cur.slayer == null ? m.slayer : Math.min(cur.slayer, m.slayer);
      } else {
        monsters.set(m.name, { ...m });
      }
    }
    for (const n of e.npcs) npcs.add(n);
    for (const [name, count] of e.objects) objects.set(name, (objects.get(name) ?? 0) + count);
    for (const s of e.shops) shops.add(s);
    for (const [q, kind] of Object.entries(e.quests)) {
      if (kind === 'first' || !(q in quests)) quests[q] = kind;
    }
    for (const [area, refs] of Object.entries(e.diaries)) {
      diaries[area] = area in diaries ? `${diaries[area]}, ${refs}` : refs;
    }
    for (const [tier, n] of Object.entries(e.clues)) clues[tier] = (clues[tier] ?? 0) + n;
    for (const s of e.spawns) spawns.add(s);
  }

  return {
    monsters: [...monsters.values()].sort((a, b) => b.count - a.count),
    npcs: [...npcs].sort(),
    objects: [...objects.entries()].sort((a, b) => b[1] - a[1]),
    shops: [...shops].sort(),
    quests,
    diaries,
    clues,
    spawns: [...spawns].sort(),
  };
}

class ChunkContentService {
  private doc: RawDoc | null = null;
  private promise: Promise<boolean> | null = null;
  error: string | null = null;

  get ready() { return this.doc != null; }

  /** Idempotent lazy init; resolves false (and sets .error) on failure. */
  init(): Promise<boolean> {
    if (this.doc) return Promise.resolve(true);
    if (!this.promise) {
      const base = (import.meta as any).env?.BASE_URL ?? '/';
      this.promise = fetch(`${base}chunk-content.json`)
        .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); })
        .then((doc: RawDoc) => { this.doc = doc; return true; })
        .catch((err: Error) => {
          this.error = err.message;
          this.promise = null; // allow retry
          return false;
        });
    }
    return this.promise;
  }

  contentFor(cx: number, cy: number): ChunkContent | null {
    const e = this.doc?.chunks[String(cx * 256 + cy)];
    return e ? decode(e) : null;
  }

  /** Region-level aggregate over a chunk list (missing chunks are skipped). */
  aggregate(chunks: { cx: number; cy: number }[]): ChunkContent {
    const entries: ChunkContent[] = [];
    for (const { cx, cy } of chunks) {
      const c = this.contentFor(cx, cy);
      if (c) entries.push(c);
    }
    return aggregateContent(entries);
  }
}

export const chunkContentService = new ChunkContentService();
