import { isRunelitePairCode } from '../utils/runelitePairing';

/**
 * Online relay sync (optional). Pushes the run bundle to a hosted Cloudflare
 * Worker under a short pairing code; the RuneLite plugin polls it by that code.
 * Outbound-only on both sides — see workers/fate-relay + docs/online-relay.md.
 *
 * Holds the session (code + private write-token) and a tiny pub/sub so the UI
 * and the always-mounted driver stay in sync. No data leaves until the user
 * explicitly enables it.
 */
const DEFAULT_BASE = 'https://fate-relay.fatelocked.workers.dev';
const SESSION_KEY = 'fate_relay_session_v1';
const BASE_KEY = 'fate_relay_base';

export type RelayStatus = 'off' | 'syncing' | 'synced' | 'error';

interface Session { code: string; token: string; }

// Crockford base32 (no ambiguous 0/O/1/I/L/U) for a readable pairing code.
const ALPHABET = '23456789ABCDEFGHJKMNPQRSTVWXYZ';
function randomCode(len = 8): string {
  const a = crypto.getRandomValues(new Uint8Array(len));
  return Array.from(a, (x) => ALPHABET[x % ALPHABET.length]).join('');
}
function randomToken(): string {
  const a = crypto.getRandomValues(new Uint8Array(18));
  return Array.from(a, (x) => x.toString(16).padStart(2, '0')).join('');
}

export class RelaySyncService {
  private session: Session | null = null;
  private pendingPush: Promise<void> | null = null;
  private activeRequest: AbortController | null = null;

  private resetQueue() {
    this.activeRequest?.abort();
    this.activeRequest = null;
    this.pendingPush = null;
  }
  private listeners = new Set<() => void>();

  status: RelayStatus = 'off';
  lastError: string | null = null;
  lastSyncAt: number | null = null;
  pushRequestRevision = 0;

  constructor() {
    try {
      const raw = localStorage.getItem(SESSION_KEY);
      if (raw) this.session = JSON.parse(raw);
    } catch { /* ignore */ }
  }

  get enabled() { return this.session != null; }
  get code() { return this.session?.code ?? null; }

  base(): string {
    const env = (import.meta as any).env?.VITE_FATE_RELAY as string | undefined;
    let ls: string | null = null;
    try { ls = localStorage.getItem(BASE_KEY); } catch { /* ignore */ }
    return (env || ls || DEFAULT_BASE).replace(/\/$/, '');
  }

  subscribe(fn: () => void) { this.listeners.add(fn); return () => { this.listeners.delete(fn); }; }
  private emit() { for (const fn of this.listeners) fn(); }

  /** Adopt the private pairing identity generated by RuneLite. */
  adoptCode(code: string): boolean {
    if (!isRunelitePairCode(code)) return false;
    const nextSession = { code, token: randomToken() };
    try {
      localStorage.setItem(SESSION_KEY, JSON.stringify(nextSession));
    } catch {
      return false;
    }
    this.resetQueue();
    this.session = nextSession;
    this.status = 'syncing';
    this.lastError = null;
    this.lastSyncAt = null;
    this.pushRequestRevision += 1;
    this.emit();
    return true;
  }

  /** Start a new session: fresh code + private write-token. */
  enable(): string {
    this.resetQueue();
    this.session = { code: randomCode(), token: randomToken() };
    try { localStorage.setItem(SESSION_KEY, JSON.stringify(this.session)); } catch { /* ignore */ }
    this.status = 'syncing';
    this.lastError = null;
    this.lastSyncAt = null;
    this.pushRequestRevision += 1;
    this.emit();
    return this.session.code;
  }

  disable() {
    this.resetQueue();
    this.session = null;
    try { localStorage.removeItem(SESSION_KEY); } catch { /* ignore */ }
    this.status = 'off';
    this.lastError = null;
    this.lastSyncAt = null;
    this.emit();
  }

  /** Ask the mounted driver to rebuild and send the current profile. */
  requestPush(): boolean {
    if (!this.session) return false;
    this.status = 'syncing';
    this.lastError = null;
    this.pushRequestRevision += 1;
    this.emit();
    return true;
  }

  /** Surface a bundle-build failure owned by the current session. */
  reportPushFailure(error: unknown): void {
    if (!this.session) return;
    this.status = 'error';
    this.lastError = error instanceof Error
      ? error.message
      : String(error || 'bundle build failed');
    this.emit();
  }

  /** Push a (compressed) bundle payload to the relay. No-op when disabled. */
  push(payload: string, isCurrent: () => boolean = () => true): Promise<boolean> {
    const session = this.session;
    if (!session) return Promise.resolve(false);
    // An older POST must settle before a newer profile replaces it. Re-check
    // queued work at dispatch, since a profile can change while it waits.
    const publish = () => this.publish(payload, session, isCurrent);
    const result = this.pendingPush ? this.pendingPush.then(publish, publish) : publish();
    const settled = result.then(() => {}, () => {});
    this.pendingPush = settled;
    void settled.then(() => { if (this.pendingPush === settled) this.pendingPush = null; });
    return result;
  }

  private async publish(payload: string, session: Session, isCurrent: () => boolean): Promise<boolean> {
    if (this.session !== session || !isCurrent()) return false;
    this.status = 'syncing';
    this.lastError = null;
    this.emit();
    const request = new AbortController();
    this.activeRequest = request;
    const timeout = setTimeout(() => request.abort(), 20_000);
    const cancelled = new Promise<never>((_, reject) => {
      request.signal.addEventListener('abort', () => reject(new Error('Sync request cancelled or timed out. Try again.')), { once: true });
    });
    try {
      const res = await Promise.race([fetch(`${this.base()}/r/${session.code}`, {
        signal: request.signal,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token: session.token, payload }),
      }), cancelled]);
      if (!res.ok) throw new Error(`relay ${res.status}`);
      if (this.session !== session || !isCurrent()) return false;
      this.status = 'synced';
      this.lastSyncAt = Date.now();
      this.lastError = null;
      this.emit();
      return true;
    } catch (e: any) {
      if (this.session !== session || !isCurrent()) return false;
      this.status = 'error';
      this.lastError = e?.message ?? 'push failed';
      this.emit();
      return false;
    } finally {
      clearTimeout(timeout);
      if (this.activeRequest === request) this.activeRequest = null;
    }
  }

  /** POST to an app-owned structured sub-resource using the private session token. */
  async postOwnedSubresource(path: string, body: Record<string, unknown>): Promise<boolean> {
    if (!this.session) return false;
    try {
      const suffix = path.startsWith('/') ? path : `/${path}`;
      const res = await fetch(`${this.base()}/r/${this.session.code}${suffix}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token: this.session.token, ...body }),
      });
      return res.ok;
    } catch {
      return false;
    }
  }

}

export const relaySync = new RelaySyncService();
