import { isRunelitePairCode } from '../utils/runelitePairing';

/**
 * Online relay sync (optional). Pushes the run bundle to a hosted Cloudflare
 * Worker under a short pairing code; the RuneLite plugin polls it by that code.
 * Outbound-only on both sides — see workers/fate-relay + docs/online-relay.md.
 *
 * Holds the session (code + private write-token) and a tiny pub/sub so the UI
 * and the always-mounted driver stay in sync. No data leaves until the user
 * explicitly enables it.
 */
const DEFAULT_BASE = 'https://fate-relay.fatelocked.workers.dev';
const SESSION_KEY = 'fate_relay_session_v1';
const BASE_KEY = 'fate_relay_base';
/** A stalled POST fails after this long instead of holding up later publishes. */
const REQUEST_TIMEOUT_MS = 15_000;

export type RelayStatus = 'off' | 'syncing' | 'synced' | 'error';

interface Session {
  code: string;
  token: string;
  /** The profile this pairing publishes. Pairings saved before it was
   *  recorded have none; the first tab to publish one binds it. */
  profileId?: string;
}

const sameSession = (a: Session | null, b: Session | null): boolean =>
  a?.code === b?.code && a?.token === b?.token && a?.profileId === b?.profileId;

/** The stored pairing, or undefined when storage can't be read. */
function readStoredSession(): Session | null | undefined {
  let raw: string | null;
  try { raw = localStorage.getItem(SESSION_KEY); } catch { return undefined; }
  try {
    const parsed = raw ? JSON.parse(raw) : null;
    return parsed && typeof parsed.code === 'string' && typeof parsed.token === 'string'
      ? parsed
      : null;
  } catch {
    return null;
  }
}

// Crockford base32 (no ambiguous 0/O/1/I/L/U) for a readable pairing code.
const ALPHABET = '23456789ABCDEFGHJKMNPQRSTVWXYZ';
function randomCode(len = 8): string {
  const a = crypto.getRandomValues(new Uint8Array(len));
  return Array.from(a, (x) => ALPHABET[x % ALPHABET.length]).join('');
}
function randomToken(): string {
  const a = crypto.getRandomValues(new Uint8Array(18));
  return Array.from(a, (x) => x.toString(16).padStart(2, '0')).join('');
}

export class RelaySyncService {
  private session: Session | null = null;
  /** The profile this tab shows. Every tab shares the one stored pairing. */
  private activeProfileId: string | null = null;
  private pushQueue: Promise<unknown> = Promise.resolve();
  private listeners = new Set<() => void>();

  status: RelayStatus = 'off';
  lastError: string | null = null;
  lastSyncAt: number | null = null;
  pushRequestRevision = 0;

  constructor() {
    this.session = readStoredSession() ?? null;
    // Pairing, re-pairing, binding and Disconnect in other tabs.
    if (typeof window !== 'undefined') {
      window.addEventListener('storage', (event) => {
        if (event.key !== SESSION_KEY && event.key !== null) return;
        const stored = readStoredSession();
        if (stored !== undefined) this.adoptStored(stored);
      });
    }
  }

  /** Paired with the profile this tab shows, or with no profile yet. Only
   *  then may this tab publish, or show RuneLite as connected. */
  get enabled() {
    const pairedProfile = this.session?.profileId;
    return this.session != null
      && (pairedProfile === undefined || pairedProfile === this.activeProfileId);
  }
  get code() { return this.enabled && this.session ? this.session.code : null; }

  /**
   * Record the profile this tab shows. App's GameProviderBridge calls this
   * while rendering, before anything below it reads `enabled`; it doesn't
   * emit, because switching profile remounts every reader.
   */
  setActiveProfile(profileId: string | null): void {
    this.activeProfileId = profileId;
  }

  base(): string {
    const env = (import.meta as any).env?.VITE_FATE_RELAY as string | undefined;
    let ls: string | null = null;
    try { ls = localStorage.getItem(BASE_KEY); } catch { /* ignore */ }
    return (env || ls || DEFAULT_BASE).replace(/\/$/, '');
  }

  subscribe(fn: () => void) { this.listeners.add(fn); return () => { this.listeners.delete(fn); }; }
  private emit() { for (const fn of this.listeners) fn(); }

  /** Adopt the private pairing identity generated by RuneLite, for a profile. */
  adoptCode(code: string, profileId: string | null = this.activeProfileId): boolean {
    if (!isRunelitePairCode(code)) return false;
    const nextSession: Session = {
      code, token: randomToken(), ...(profileId != null ? { profileId } : {}),
    };
    try {
      localStorage.setItem(SESSION_KEY, JSON.stringify(nextSession));
    } catch {
      return false;
    }
    this.session = nextSession;
    this.status = 'syncing';
    this.lastError = null;
    this.lastSyncAt = null;
    this.pushRequestRevision += 1;
    this.emit();
    return true;
  }

  /** Start a new session: fresh code + private write-token. */
  enable(profileId: string | null = this.activeProfileId): string {
    this.session = {
      code: randomCode(), token: randomToken(), ...(profileId != null ? { profileId } : {}),
    };
    try { localStorage.setItem(SESSION_KEY, JSON.stringify(this.session)); } catch { /* ignore */ }
    this.status = 'syncing';
    this.lastError = null;
    this.lastSyncAt = null;
    this.pushRequestRevision += 1;
    this.emit();
    return this.session.code;
  }

  disable() {
    this.session = null;
    try { localStorage.removeItem(SESSION_KEY); } catch { /* ignore */ }
    this.status = 'off';
    this.lastError = null;
    this.lastSyncAt = null;
    this.emit();
  }

  /** Ask the mounted driver to rebuild and send the current profile. */
  requestPush(): boolean {
    if (!this.enabled) return false;
    this.status = 'syncing';
    this.lastError = null;
    this.pushRequestRevision += 1;
    this.emit();
    return true;
  }

  /** Surface a bundle-build failure owned by the current session. */
  reportPushFailure(error: unknown): void {
    if (!this.enabled) return;
    this.status = 'error';
    this.lastError = error instanceof Error
      ? error.message
      : String(error || 'bundle build failed');
    this.emit();
  }

  /** Push a (compressed) bundle payload to the relay. No-op when disabled. */
  push(payload: string, isCurrent: () => boolean = () => true): Promise<boolean> {
    this.bindToActiveProfile();
    const session = this.session;
    if (!session || !this.enabled) return Promise.resolve(false);
    // Replacing, re-binding or disconnecting the pairing, here or in another
    // tab, drops the write.
    const current = () => this.enabled && this.session?.code === session.code
      && this.session.token === session.token && isCurrent();
    // Complete network writes in order across driver unmounts/profile switches.
    // A cancelled queued build never publishes; an already-sent write finishes
    // before the current profile's write, so the relay cannot end on stale data.
    const send = this.pushQueue.then(() => {
      if (!current()) return false;
      return this.sendPayload(payload, session, current);
    });
    this.pushQueue = send.catch(() => false);
    return send;
  }

  /**
   * A pairing saved before profiles were recorded goes to the first tab that
   * publishes it (the choice is written back for every tab). Storage is read
   * first: another tab may already have bound or replaced it, with its
   * storage event still on the way.
   */
  private bindToActiveProfile(): void {
    const session = this.session;
    if (!session || session.profileId !== undefined || this.activeProfileId === null) return;
    const stored = readStoredSession();
    if (stored !== undefined && !sameSession(stored, session)) {
      this.adoptStored(stored);
      return;
    }
    const bound: Session = { ...session, profileId: this.activeProfileId };
    try { localStorage.setItem(SESSION_KEY, JSON.stringify(bound)); } catch { /* this tab only */ }
    this.session = bound;
  }

  /** Take the pairing another tab stored: paired, re-paired, bound or disconnected. */
  private adoptStored(next: Session | null): void {
    if (sameSession(next, this.session)) return;
    const previousCode = this.code;
    this.session = next;
    if (!this.enabled) {
      this.status = 'off';
      this.lastError = null;
      this.lastSyncAt = null;
    } else if (this.code !== previousCode) {
      // Paired again for this profile; the driver publishes it from here too.
      this.status = 'syncing';
      this.lastError = null;
      this.lastSyncAt = null;
    }
    this.emit();
  }

  private async sendPayload(payload: string, session: Session, isCurrent: () => boolean): Promise<boolean> {
    this.status = 'syncing';
    this.lastError = null;
    this.emit();
    try {
      const res = await this.post(`/r/${session.code}`, { token: session.token, payload });
      if (!res.ok) throw new Error(`relay ${res.status}`);
      if (!isCurrent()) return false;
      this.status = 'synced';
      this.lastSyncAt = Date.now();
      this.lastError = null;
      this.emit();
      return true;
    } catch (e: any) {
      if (!isCurrent()) return false;
      this.status = 'error';
      this.lastError = e?.message ?? 'push failed';
      this.emit();
      return false;
    }
  }

  /** POST to an app-owned structured sub-resource using the private session token. */
  async postOwnedSubresource(path: string, body: Record<string, unknown>): Promise<boolean> {
    if (!this.enabled || !this.session) return false;
    try {
      const suffix = path.startsWith('/') ? path : `/${path}`;
      const res = await this.post(`/r/${this.session.code}${suffix}`, {
        token: this.session.token, ...body,
      });
      return res.ok;
    } catch {
      return false;
    }
  }

  /** JSON POST to the relay that rejects (and aborts) after REQUEST_TIMEOUT_MS. */
  private async post(path: string, body: Record<string, unknown>): Promise<Response> {
    const controller = new AbortController();
    let timer: ReturnType<typeof setTimeout> | undefined;
    // Race as well as abort, so a request that ignores the signal still ends.
    const timedOut = new Promise<never>((_, reject) => {
      timer = setTimeout(() => {
        controller.abort();
        reject(new Error('relay timed out'));
      }, REQUEST_TIMEOUT_MS);
    });
    try {
      return await Promise.race([
        fetch(`${this.base()}${path}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
          signal: controller.signal,
        }),
        timedOut,
      ]);
    } finally {
      clearTimeout(timer);
    }
  }
}

export const relaySync = new RelaySyncService();
