/**
 * Builds data/chunkSkillNodes.ts: for each land chunk, the lowest tier at
 * which each skill can be trained there, from public/chunk-content.json. Chunked
 * mode's Skills rolls read it (utils/chunkedSkillPool.ts), so a Skills Key
 * only lands on a skill the run's chunks have something for.
 *
 * Besides real skills, three facts feed derived skills at roll time:
 *   @monster  something to fight (melee, Ranged, Magic, Prayer from bones)
 *   @slayer   a Slayer master
 *   @herb     a herb patch (Herblore's herbs)
 * Interiors count for the chunk they are entered from, when that entrance has
 * no requirements.
 */
import { trainingReqFor } from './skillChunkNodes';
import type { EntityKind } from '../services/ChunkContentService';
import { ALL_CHUNK_KEYS } from './chunkAdjacency';
import { tierForLevel } from './skillTiers';

type RawEntry = { m?: [string, number, number?][]; p?: string[]; o?: [string, number][] };
interface RawDoc {
  chunks: Record<string, RawEntry>;
  interiors?: Record<string, { content: RawEntry; entrances: { chunkId: string; requirements: string[] }[] }>;
  slayerMasters?: Record<string, unknown>;
}

export type ChunkSkillNodes = Record<string, Record<string, number>>;

const HERB_PATCH = /\bherb patch\b/i;

export function buildChunkSkillNodes(doc: RawDoc): ChunkSkillNodes {
  const masters = new Set(Object.keys(doc.slayerMasters ?? {}));
  const entriesById = new Map<string, RawEntry[]>();
  const add = (id: string, entry: RawEntry) => entriesById.set(id, [...(entriesById.get(id) ?? []), entry]);
  for (const [id, entry] of Object.entries(doc.chunks)) add(id, entry);
  for (const interior of Object.values(doc.interiors ?? {})) {
    for (const route of interior.entrances) if (route.requirements.length === 0) add(route.chunkId, interior.content);
  }
  const out: ChunkSkillNodes = {};
  for (const id of [...entriesById.keys()].sort((a, b) => Number(a) - Number(b))) {
    const facts: Record<string, number> = {};
    const note = (skill: string, level: number) => { facts[skill] = Math.min(facts[skill] ?? level, level); };
    for (const entry of entriesById.get(id)!) {
      const named: [string, EntityKind][] = [
        ...(entry.o ?? []).map(([name]) => [name, 'object'] as [string, EntityKind]),
        ...(entry.p ?? []).map((name) => [name, 'npc'] as [string, EntityKind]),
        ...(entry.m ?? []).map(([name]) => [name, 'monster'] as [string, EntityKind]),
      ];
      for (const [name, kind] of named) {
        const req = trainingReqFor(name, kind);
        if (req) note(req.skill, req.level);
        if (kind === 'object' && HERB_PATCH.test(name)) note('@herb', 1);
        if (kind !== 'object' && masters.has(name)) note('@slayer', 1);
      }
      if ((entry.m ?? []).length > 0) note('@monster', 1);
    }
    const value = Number(id);
    const key = `${Math.floor(value / 256)},${value % 256}`;
    if (Object.keys(facts).length === 0 || !LAND.has(key)) continue;
    out[key] = facts;
  }
  return out;
}

const LAND = new Set(ALL_CHUNK_KEYS);

/**
 * The generated file stores one string per chunk, one character per fact in
 * CHUNK_SKILL_FACTS order: the tier of the lowest level the fact needs (1-9,
 * 0 for tier 10) or "." when the chunk has none. Compact because the roll
 * engine loads it with the app's first screen.
 */
export const chunkSkillNodesSource = (nodes: ChunkSkillNodes): string => {
  const facts = [...new Set(Object.values(nodes).flatMap(Object.keys))].sort();
  const rows = Object.fromEntries(Object.entries(nodes).map(([key, levels]) => [key,
    facts.map(fact => levels[fact] === undefined ? '.' : String(tierForLevel(levels[fact]) % 10)).join('').replace(/\.+$/, '')]));
  return `// AUTO-GENERATED by scripts/buildChunkSkillNodes.ts from public/chunk-content.json — do not edit by hand.\n`
    + `// Keyed "cx,cy"; one character per fact: the tier its lowest level needs (0 = tier 10), "." for none.\n`
    + `// See utils/chunkSkillNodesBuild.ts.\n\n`
    + `export const CHUNK_SKILL_FACTS: readonly string[] = ${JSON.stringify(facts)};\n\n`
    + `export const CHUNK_SKILL_TIERS: Readonly<Record<string, string>> = ${JSON.stringify(rows)};\n`;
};
