/**
 * QR rendering for sync links. Uses the dependency-free `qrcode-generator`
 * (MIT) and emits a crisp, scalable SVG string — nothing leaves the device, so
 * the run data (which the code effectively *is*) stays private and works
 * offline.
 *
 * Sync codes for large runs exceed what a screen-scannable QR can hold, so we
 * cap the input length: above the cap the caller should fall back to the
 * copyable link/code instead of rendering an unscannably dense QR.
 */

import qrcode from 'qrcode-generator';

/** Above this many characters a QR becomes too dense to scan from a screen. */
export const QR_MAX_CHARS = 1200;

export interface QrResult {
  ok: boolean;
  /** Inline SVG markup (safe — generated by us, no user HTML). */
  svg?: string;
  error?: string;
}

export const makeQrSvg = (data: string, margin = 4): QrResult => {
  if (!data) return { ok: false, error: 'Nothing to encode.' };
  if (data.length > QR_MAX_CHARS) {
    return { ok: false, error: 'This run is too large for a scannable QR — use the link or code instead.' };
  }
  try {
    const qr = qrcode(0, 'L'); // auto version, low ECC = max capacity
    qr.addData(data); // default Byte mode (handles base64url + URL chars)
    qr.make();

    const count = qr.getModuleCount();
    const dim = count + margin * 2;

    // One compact path of unit squares for every dark module.
    let path = '';
    for (let r = 0; r < count; r++) {
      for (let c = 0; c < count; c++) {
        if (qr.isDark(r, c)) path += `M${c + margin} ${r + margin}h1v1h-1z`;
      }
    }

    const svg =
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${dim} ${dim}" ` +
      `shape-rendering="crispEdges" width="100%" height="100%">` +
      `<rect width="${dim}" height="${dim}" fill="#ffffff"/>` +
      `<path d="${path}" fill="#0a0a0a"/></svg>`;

    return { ok: true, svg };
  } catch {
    // Thrown when the data exceeds even version-40 capacity.
    return { ok: false, error: 'This run is too large to fit in a QR code — use the link or code instead.' };
  }
};
