// AUTO-GENERATED by scripts/gen-model-manifest.mjs — do not edit by hand.
// Slugs of the 3D models present in /public/models (run `npm run models:manifest`).
export const MODEL_SLUGS: string[] = [
];
