// AUTO-GENERATED by scripts/gen-model-manifest.mjs — do not edit by hand.
// Maps an entity slug to its model file in /public/models (run `npm run models:manifest`).
export const MODEL_FILES: Record<string, string> = {
};
