// AUTO-GENERATED by `npm run models:export -- --cache <dir> --pets` - do not edit by hand.
// Every pet in data/pets.ts has a model at public/models/pets/<petId>.gltf; these have no idle
// animation (a skeletal one, or one that didn't export cleanly), so the app bobs them instead.
export const STILL_PET_MODELS: readonly number[] = [502003, 502025, 502033, 502051, 502052, 502053, 502055, 502056, 502057, 502058, 502061, 502062, 502064, 502065, 502067, 502069];
