// One-off authoring tool: pulls Herblore recipes from the OSRS Wiki `recipe`
// bucket and emits curated RESOURCE_MAP potion entries for the Resource Engine.
// Output is spliced into resourceData.ts; not shipped or imported at runtime.
//
// Run:  node scripts/buildPotions.mjs
import { execFileSync } from 'child_process';
import { readFileSync, writeFileSync } from 'fs';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)';
const API = 'https://oldschool.runescape.wiki/api.php';

const fetchRecipes = (skill) => {
  const query = `bucket('recipe').select('production_json').where('uses_skill','${skill}').limit(5000).run()`;
  const url = `${API}?action=bucket&format=json&query=${encodeURIComponent(query)}`;
  const body = execFileSync('curl', ['-s', '-A', UA, url], { encoding: 'utf8', maxBuffer: 5e7 });
  const json = JSON.parse(body);
  if (!json.bucket) throw new Error(`No bucket for ${skill}`);
  return json.bucket.map((r) => JSON.parse(r.production_json));
};

// --- name helpers -----------------------------------------------------------
const CONNECTORS = new Set(['of', 'the', 'a', 'an', 'and', 'to', 'on', 'from']);
const toAppCase = (raw) =>
  raw.trim().split(' ').map((w, i) => {
    const lower = w.toLowerCase();
    if (i > 0 && CONNECTORS.has(lower)) return lower;
    return w.charAt(0).toUpperCase() + w.slice(1);
  }).join(' ');

const isUnf = (name) => /\(unf\)/i.test(name);
const stripDose = (name) =>
  name
    .replace(/\s*\(\s*\d\s*\)\s*$/i, '')   // trailing dose "(3)"
    .replace(/\s*\(\s*\+\s*\)/g, '+')       // wiki "(+)" -> "+"
    .replace(/\s*\(\s*-\s*\)/g, '-')        // wiki "(-)" -> "-"
    .trim();

// Mastering Mixology potions are brewed in the minigame from a "water-filled
// gourd vial" and special herbs (golpar, noxifer, buchu leaf, cicely, etc.).
// They need a minigame unlock and have awkward +/- naming, so we exclude them
// from the standard-potion import. Every MM potion uses the gourd vial.
const isMixologyMaterial = (name) =>
  /gourd vial/i.test(name) ||
  /\b(mox|aga|lye)\b/i.test(name) ||
  /(paste|resin)/i.test(name) ||
  /\b(noxifer|golpar|buchu leaf|cicely|stinkhorn|endarkened|aldarium)\b/i.test(name);

// Materials that should match existing RESOURCE_MAP keys.
const INPUT_ALIAS = { 'Runite Bar': 'Rune Bar' };

// --- existing RESOURCE_MAP keys (skip collisions) ---------------------------
const dataPath = new URL('../data/resourceData.ts', import.meta.url);
let src = readFileSync(dataPath, 'utf8');
if (src.includes('POTIONS (generated by')) {
  throw new Error('resourceData.ts already contains a generated potions block.');
}
const EOL = src.includes('\r\n') ? '\r\n' : '\n';
const mapBody = src.slice(src.indexOf('RESOURCE_MAP'), src.indexOf('// --- CATEGORY GROUPING'));
const existing = new Set(
  [...mapBody.matchAll(/^\s{2}'((?:[^'\\]|\\.)*)':\s*\[/gm)].map((m) =>
    m[1].replace(/\\'/g, "'").toLowerCase(),
  ),
);

// --- gather recipes ---------------------------------------------------------
const recipes = fetchRecipes('Herblore');

// unfinished-potion recipes: output "X potion (unf)" -> [herb, vial]
const unfMap = {};
for (const r of recipes) {
  const out = r.output?.name;
  if (out && isUnf(out)) {
    unfMap[out] = (r.materials || []).map((m) => ({
      name: m.name,
      qty: Number(m.quantity) || 1,
    }));
  }
}

const norm = (n) => {
  const cased = toAppCase(stripDose(n));
  return INPUT_ALIAS[cased] || cased;
};

const items = new Map();
let skippedExisting = 0;

for (const r of recipes) {
  const out = r.output?.name;
  if (!out || isUnf(out)) continue;
  if (!/\(\s*\d\s*\)\s*$/.test(out)) continue;      // potions are dosed
  if (/\bmix\(\d\)/i.test(out)) continue;            // skip Barbarian potion mixes

  const base = stripDose(out);
  if (isUnf(base) || /^Mixture\b/i.test(base)) continue;        // quest/unf junk
  if (/[()]/.test(base)) continue;                              // leftover odd naming
  if ((r.materials || []).some((m) => isMixologyMaterial(m.name))) continue;

  const skill = r.skills?.find((s) => s.name === 'Herblore');
  if (!skill) continue;

  // Build inputs, expanding any unfinished-potion material into herb + vial.
  const inputs = {};
  let isDecant = false;
  for (const m of r.materials || []) {
    if (isUnf(m.name)) {
      for (const sub of unfMap[m.name] || []) {
        inputs[norm(sub.name)] = (inputs[norm(sub.name)] || 0) + sub.qty;
      }
    } else {
      const key = norm(m.name);
      if (key === toAppCase(base)) isDecant = true; // decant: same potion as material
      inputs[key] = (inputs[key] || 0) + (Number(m.quantity) || 1);
    }
  }
  if (isDecant || Object.keys(inputs).length === 0) continue;

  const key = toAppCase(base);
  if (existing.has(key.toLowerCase())) { skippedExisting++; continue; }

  const source = {
    type: 'SKILL',
    name: 'Herblore',
    skills: { Herblore: Number(skill.level) || 1 },
    inputs,
  };
  const sig = JSON.stringify(source);
  if (!items.has(key)) items.set(key, []);
  if (!items.get(key).some((s) => JSON.stringify(s) === sig)) items.get(key).push(source);
}

// Collapse multi-dose recipe rows: the wiki lists e.g. Super antifire once per
// dose, identical apart from one scaling ingredient quantity. Keep a single
// representative (the lowest-quantity row) per skill-level + ingredient set.
for (const [key, list] of items) {
  const groups = new Map();
  for (const s of list) {
    const g = `${s.name}|${JSON.stringify(s.skills)}|${Object.keys(s.inputs).sort().join(',')}`;
    const sum = Object.values(s.inputs).reduce((a, b) => a + b, 0);
    const cur = groups.get(g);
    if (!cur || sum < cur.sum) groups.set(g, { source: s, sum });
  }
  items.set(key, [...groups.values()].map((v) => v.source));
}

// --- emit TS ----------------------------------------------------------------
const esc = (s) => s.replace(/'/g, "\\'");
const fmt = (s) =>
  `{ type: 'SKILL', name: 'Herblore', regions: ['Any'], ` +
  `skills: { 'Herblore': ${s.skills.Herblore} }, ` +
  `inputs: { ${Object.entries(s.inputs).map(([k, v]) => `'${esc(k)}': ${v}`).join(', ')} } }`;

const keys = [...items.keys()].sort();
let ts = '';
for (const key of keys) {
  ts += `  '${esc(key)}': [${EOL}`;
  ts += items.get(key).map((s) => `    ${fmt(s)}`).join(`,${EOL}`) + EOL;
  ts += `  ],${EOL}`;
}

// --- splice into resourceData.ts -------------------------------------------
const mapAnchor = `  ],${EOL}};${EOL}${EOL}// --- CATEGORY GROUPING`;
if (!src.includes(mapAnchor)) throw new Error('RESOURCE_MAP anchor not found.');
src = src.replace(
  mapAnchor,
  `  ],${EOL}${EOL}  // --- POTIONS (generated by scripts/buildPotions.mjs) ---${EOL}${ts}};${EOL}${EOL}// --- CATEGORY GROUPING`,
);

// Append the new potion names into the existing 'Potions' category array.
const catAnchor = `'Super Energy(4)',${EOL}  ],`;
if (!src.includes(catAnchor)) throw new Error("'Potions' category anchor not found.");
const catLines = keys.map((k) => `    '${esc(k)}',`).join(EOL);
src = src.replace(catAnchor, `'Super Energy(4)',${EOL}${catLines}${EOL}  ],`);

writeFileSync(dataPath, src);
console.log(`Spliced ${keys.length} potions into data/resourceData.ts (skipped ${skippedExisting} existing).`);
console.log(keys.join(', '));
