import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  bankLocationLabels,
  bankVirtualLocations,
  readBankLocationRegistry,
  validateBankLocationRegistry,
} from './bank-locations.mjs';
import { generatedTextMatches } from './generated-text.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DOC_PATH = resolve(ROOT, 'public', 'chunk-content.json');
const OUTPUT_PATH = resolve(ROOT, 'data', 'banks.ts');

export function buildBankDefinitions(doc, registry) {
  const chunks = doc.chunks ?? {};
  const labels = bankLocationLabels(registry);
  const bankIds = [...new Set((doc.banks ?? []).map(String))];
  const physicalDefs = bankIds
    .map(id => ({ id, name: (labels.get(id) ?? chunks[id]?.n ?? chunks[id]?.name ?? `Bank ${id}`).trim() }))
    .sort((a, b) => a.name.localeCompare(b.name));
  const virtualDefs = bankVirtualLocations(registry)
    .map(({ id, name }) => ({ id, name: name.trim() }));
  const defs = [...physicalDefs, ...virtualDefs];

  const seen = new Set();
  for (const def of defs) {
    if (seen.has(def.name)) def.name = `${def.name} (${def.id})`;
    seen.add(def.name);
  }
  return defs;
}

export function generateBankSource(doc, registry) {
  const defs = buildBankDefinitions(doc, registry);
  const physicalCount = new Set((doc.banks ?? []).map(String)).size;
  const virtualCount = bankVirtualLocations(registry).length;
  const body = defs.map(def => `  { id: '${def.id}', name: ${JSON.stringify(def.name)} },`).join('\n');
  return `// AUTO-GENERATED by scripts/gen-banks.mjs — do not edit by hand.
// The ${defs.length} bankable unlocks: ${physicalCount} physical chunk entries plus
// ${virtualCount} virtual registry entries. Each is its own unlock in bank-locked modes.
// Physical entries are keyed by canonical chunk id "cx*256+cy".

export interface BankDef { id: string; name: string }

export const BANKS: BankDef[] = [
${body}
];

/** All bank ids, for the roll pool. */
export const BANK_IDS: string[] = BANKS.map((b) => b.id);

/** id → definition, for label lookups. */
export const BANK_BY_ID: Record<string, BankDef> =
  Object.fromEntries(BANKS.map((b) => [b.id, b]));

/** Canonical chunk id for a chunk coordinate — the bank's unlock key. */
export const bankId = (cx: number, cy: number): string => String(cx * 256 + cy);
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.some(arg => arg !== '--check')) throw new Error('Usage: node scripts/gen-banks.mjs [--check]');
  const doc = JSON.parse(readFileSync(DOC_PATH, 'utf8'));
  const registry = readBankLocationRegistry();
  validateBankLocationRegistry(registry, {
    validChunkIds: new Set(Object.keys(doc.chunks ?? {})),
    validBankIds: new Set((doc.banks ?? []).map(String)),
  });
  const expected = generateBankSource(doc, registry);
  if (args.includes('--check')) {
    if (!existsSync(OUTPUT_PATH) || !generatedTextMatches(readFileSync(OUTPUT_PATH, 'utf8'), expected)) {
      throw new Error('Generated bank definitions are stale: data/banks.ts');
    }
    console.log('Generated bank definitions are current.');
  } else {
    writeFileSync(OUTPUT_PATH, expected);
    console.log(`Wrote data/banks.ts with ${buildBankDefinitions(doc, registry).length} banks.`);
  }
}
