// Regenerates data/banks.ts from public/chunk-content.json's `banks` array —
// the canonical set of chunks that contain a bank or deposit box. Each becomes
// one unlockable "Bank" keyed by its canonical chunk id (cx*256+cy), named by
// the chunk's place name. Run: node scripts/gen-banks.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const doc = JSON.parse(readFileSync('public/chunk-content.json', 'utf8'));
const chunks = doc.chunks ?? {};
const bankIds = [...new Set((doc.banks ?? []).map(String))];

const defs = bankIds
  .map((id) => ({ id, name: (chunks[id]?.n ?? chunks[id]?.name ?? `Bank ${id}`).trim() }))
  .sort((a, b) => a.name.localeCompare(b.name));

// Guard: names must stay unique so they read cleanly as unlock labels.
const seen = new Map();
for (const d of defs) {
  if (seen.has(d.name)) d.name = `${d.name} (${d.id})`; // disambiguate a rare collision
  seen.set(d.name, true);
}

const body = defs.map((d) => `  { id: '${d.id}', name: ${JSON.stringify(d.name)} },`).join('\n');
const out = `// AUTO-GENERATED by scripts/gen-banks.mjs — do not edit by hand.
// The ${defs.length} bankable locations (banks + deposit boxes) from the chunk
// dataset. Each is its own unlock in bank-locked modes, keyed by canonical
// chunk id "cx*256+cy" (matches ChunkContentService.hasBank / the plugin bundle).

export interface BankDef { id: string; name: string }

export const BANKS: BankDef[] = [
${body}
];

/** All bank ids, for the roll pool. */
export const BANK_IDS: string[] = BANKS.map((b) => b.id);

/** id → definition, for label lookups. */
export const BANK_BY_ID: Record<string, BankDef> =
  Object.fromEntries(BANKS.map((b) => [b.id, b]));

/** Canonical chunk id for a chunk coordinate — the bank's unlock key. */
export const bankId = (cx: number, cy: number): string => String(cx * 256 + cy);
`;

writeFileSync('data/banks.ts', out);
console.log(`Wrote data/banks.ts with ${defs.length} banks.`);
